### ISSUE TITLE
[Bug]: Brain Creation Fails

### ISSUE THREAD

**Issue by NelsonVelazquezBF** [QuivrHQ/quivr#2186]
### What happened?

Installed a fresh installation of quivr on a RHEL 9.0 instance.  Upon trying to make a brain, I got an error with creation with just one file.

### Relevant log output

```backend-core  | ERROR:    Exception in ASGI application
backend-core  | Traceback (most recent call last):
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
backend-core  |     yield
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 100, in connect_tcp
backend-core  |     sock = socket.create_connection(
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/socket.py", line 827, in create_connection
backend-core  |     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
backend-core  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
backend-core  |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
backend-core  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  | socket.gaierror: [Errno -2] Name or service not known
backend-core  |
backend-core  | The above exception was the direct cause of the following exception:
backend-core  |
backend-core  | Traceback (most recent call last):
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
backend-core  |     yield
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 218, in handle_request
backend-core  |     resp = self._pool.handle_request(req)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 262, in handle_request
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 245, in handle_request
backend-core  |     response = connection.handle_request(request)
backend-core  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 92, in handle_request
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 69, in handle_request
backend-core  |     stream = self._connect(request)
backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 117, in _connect
backend-core  |     stream = self._network_backend.connect_tcp(**kwargs)
backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 99, in connect_tcp
backend-core  |     with map_exceptions(exc_map):
backend-core  |   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
backend-core  |     self.gen.throw(typ, value, traceback)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
backend-core  |     raise to_exc(exc) from exc
backend-core  | httpcore.ConnectError: [Errno -2] Name or service not known
backend-core  |
backend-core  | The above exception was the direct cause of the following exception:
backend-core  |
backend-core  | Traceback (most recent call last):
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
backend-core  |     result = await app(  # type: ignore[func-returns-value]
backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
backend-core  |     return await self.app(scope, receive, send)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
backend-core  |     await super().__call__(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
backend-core  |     await self.middleware_stack(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
backend-core  |     await self.app(scope, receive, _send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
backend-core  |     await self.simple_response(scope, receive, send, request_headers=headers)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
backend-core  |     await self.app(scope, receive, sender)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
backend-core  |     raise e
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
backend-core  |     await route.handle(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
backend-core  |     response = await func(request)
backend-core  |                ^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
backend-core  |     raw_response = await run_endpoint_function(
backend-core  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
backend-core  |     return await dependant.call(**values)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/modules/brain/controller/brain_routes.py", line 97, in create_new_brain
backend-core  |     user_brains = brain_user_service.get_user_brains(current_user.id)
backend-core  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/modules/brain/service/brain_user_service.py", line 127, in get_user_brains
backend-core  |     results = self.brain_user_repository.get_user_brains(user_id)  # type: ignore
backend-core  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/modules/brain/repository/brains_users.py", line 42, in get_user_brains
backend-core  |     .execute()
backend-core  |      ^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/postgrest/_sync/request_builder.py", line 57, in execute
backend-core  |     r = self.session.request(
backend-core  |         ^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 814, in request
backend-core  |     return self.send(request, auth=auth, follow_redirects=follow_redirects)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 901, in send
backend-core  |     response = self._send_handling_auth(
backend-core  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 929, in _send_handling_auth
backend-core  |     response = self._send_handling_redirects(
backend-core  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
backend-core  |     response = self._send_single_request(request)
backend-core  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1002, in _send_single_request
backend-core  |     response = transport.handle_request(request)
backend-core  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 217, in handle_request
backend-core  |     with map_httpcore_exceptions():
backend-core  |   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
backend-core  |     self.gen.throw(typ, value, traceback)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
backend-core  |     raise mapped_exc(message) from exc
backend-core  | httpx.ConnectError: [Errno -2] Name or service not known

```

**Comment by jessedegans** [comment]
You're either not authenticated or not running all containers & supabase.  postgres should give an specific error.

**Comment by NelsonVelazquezBF** [comment]
Got any suggestions as to how to validate the postgres portion?  I have tried the install on 3 different installations so I must be missing something from the installation documentation.
