### ISSUE TITLE
[Bug]: error Couldn't find package "chalk@^2.4.2"

### ISSUE THREAD

**Issue by sunnyboybaby1977** [QuivrHQ/quivr#2203]
### What happened?

error Couldn't find package "chalk@^2.4.2"

### Relevant log output

```bash
[+] Building 28.4s (13/21)                                                                               docker:default
 => [frontend internal] load build definition from Dockerfile                                                      0.3s
 => => transferring dockerfile: 2.68kB                                                                             0.0s
 => [frontend internal] load metadata for docker.io/library/node:18.19.0-alpine                                    2.1s
 => [frontend internal] load .dockerignore                                                                         0.2s
 => => transferring context: 340B                                                                                  0.0s
 => [frontend internal] load build context                                                                         0.4s
 => => transferring context: 82.54kB                                                                               0.1s
 => [frontend base 1/1] FROM docker.io/library/node:18.19.0-alpine@sha256:0085670310d2879621f96a4216c893f92e2ded8  0.0s
 => CACHED [frontend builder 1/4] WORKDIR /app                                                                     0.0s
 => CACHED [frontend runner 2/8] RUN addgroup --system --gid 1001 nodejs                                           0.0s
 => CACHED [frontend runner 3/8] RUN adduser --system --uid 1001 nextjs                                            0.1s
 => CACHED [frontend deps 1/5] RUN apk add --no-cache libc6-compat python3 make g++                                0.0s
 => CACHED [frontend deps 2/5] RUN yarn global add node-gyp                                                        0.0s
 => CACHED [frontend deps 3/5] WORKDIR /app                                                                        0.0s
 => CACHED [frontend deps 4/5] COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./                  0.0s
 => ERROR [frontend deps 5/5] RUN     if [ -f yarn.lock ]; then yarn --frozen-lockfile;     elif [ -f package-lo  24.3s
------
 > [frontend deps 5/5] RUN     if [ -f yarn.lock ]; then yarn --frozen-lockfile;     elif [ -f package-lock.json ]; then npm ci;     elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile;     else echo "Lockfile not found." && exit 1;     fi:
1.336 yarn install v1.22.19
1.413 [1/4] Resolving packages...
23.71 error Couldn't find package "chalk@^2.4.2" required by "@babel/highlight@^7.23.4" on the "npm" registry.
23.71 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
23.72 Error: Couldn't find package "chalk@^2.4.2" required by "@babel/code-frame@^7.0.0" on the "npm" registry.
23.72     at MessageError.ExtendableBuiltin (/opt/yarn-v1.22.19/lib/cli.js:721:66)
23.72     at new MessageError (/opt/yarn-v1.22.19/lib/cli.js:750:123)
23.72     at PackageRequest.<anonymous> (/opt/yarn-v1.22.19/lib/cli.js:36590:17)
23.72     at Generator.throw (<anonymous>)
23.72     at step (/opt/yarn-v1.22.19/lib/cli.js:310:30)
23.72     at /opt/yarn-v1.22.19/lib/cli.js:323:13
23.72     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
------
failed to solve: process "/bin/sh -c if [ -f yarn.lock ]; then yarn --frozen-lockfile;     elif [ -f package-lock.json ]; then npm ci;     elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile;     else echo \"Lockfile not found.\" && exit 1;     fi" did not complete successfully: exit code: 1
PS C:\Quivr>
```

**Comment by jackleeforce** [comment]
same issue with me.

**Comment by Macbook-Specter** [comment]
same issue with me.I hope the boss can help me.
