### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by wangshuai-wuhan** [QuivrHQ/quivr#2350]
### What happened?

TypeError: 'NoneType' object is not iterable

### Relevant log output

```bash
brain_sync (celery_worker.process_integration_brain_sync)
2024-03-16 08:35:00 worker        | [2024-03-16 00:35:00,003: INFO/MainProcess] Task celery_worker.process_integration_brain_sync[5fdf09d6-26b7-42f2-9ad2-b4a6b27186c2] received
2024-03-16 08:35:00 worker        | [2024-03-16 00:35:00,068: INFO/ForkPoolWorker-2] HTTP Request: GET http://host.docker.internal:54321/rest/v1/integrations_user?select=%2A%2C%20integrations%20%28%29&integrations.integration_name=eq.notion "HTTP/1.1 200 OK"
2024-03-16 08:35:00 worker        | [2024-03-16 00:35:00,092: ERROR/ForkPoolWorker-2] Task celery_worker.process_integration_brain_sync[5fdf09d6-26b7-42f2-9ad2-b4a6b27186c2] raised unexpected: TypeError("'NoneType' object is not iterable")
2024-03-16 08:35:00 worker        | Traceback (most recent call last):
2024-03-16 08:35:00 worker        |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
2024-03-16 08:35:00 worker        |     R = retval = fun(*args, **kwargs)
2024-03-16 08:35:00 worker        |                  ^^^^^^^^^^^^^^^^^^^^
2024-03-16 08:35:00 worker        |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
2024-03-16 08:35:00 worker        |     return self.run(*args, **kwargs)
2024-03-16 08:35:00 worker        |            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-16 08:35:00 worker        |   File "/code/celery_worker.py", line 192, in process_integration_brain_sync
2024-03-16 08:35:00 worker        |     for integration in integrations:
2024-03-16 08:35:00 worker        | TypeError: 'NoneType' object is not iterable
2024-03-16 08:35:26 backend-core  | INFO:     127.0.0.1:54088 - "GET /healthz HTTP/1.1" 200 OK
2024-03-16 08:35:56 backend-core  | INFO:     127.0.0.1:54144 - "GET /healthz HTTP/1.1" 200 OK
```

**Comment by wangshuai-wuhan** [comment]
how to address TypeError: 'NoneType' object is not iterable
