### ISSUE TITLE
[Bug]: 'NoneType' object is not iterable"

### ISSUE THREAD

**Issue by wangshuai-wuhan** [QuivrHQ/quivr#2352]
### What happened?

A bug happened!

### Relevant log output

```bash
Flower
Workers
Tasks
Broker
Documentation
celery_worker.process_integration_brain_sync 04cedd50-9c9d-4890-8a78-9d02ff4d2383
Name	celery_worker.process_integration_brain_sync
UUID	04cedd50-9c9d-4890-8a78-9d02ff4d2383
State	FAILURE
args	()
kwargs	{}
Result	None
Received	2024-03-16 06:00:00.055636 UTC
Started	2024-03-16 06:00:00.068868 UTC
Failed	2024-03-16 06:00:00.278617 UTC
Retries	0
Worker	celery@09380365e244
Exception	TypeError("'NoneType' object is not iterable")
Timestamp	2024-03-16 06:00:00.278617 UTC
Traceback	
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/celery_worker.py", line 192, in process_integration_brain_sync
    for integration in integrations:
TypeError: 'NoneType' object is not iterable
Clock	2853
Root	<Task: celery_worker.process_integration_brain_sync(04cedd50-9c9d-4890-8a78-9d02ff4d2383) FAILURE clock:2853>
Root id	04cedd50-9c9d-4890-8a78-9d02ff4d2383
Children
```

**Comment by wangshuai-wuhan** [comment]
@dosu-bot 2024-03-16 13:22:54 web           |  [AuthRetryableFetchError: fetch failed] {
2024-03-16 13:22:54 web           |   __isAuthError: true,
2024-03-16 13:22:54 web           |   name: 'AuthRetryableFetchError',
2024-03-16 13:22:54 web           |   status: 0
2024-03-16 13:22:54 web           | }
2024-03-16 13:22:54 web           |  [TypeError: fetch failed] {
2024-03-16 13:22:54 web           |   cause:  [Error: connect ECONNREFUSED 127.0.0.1:54321] {
2024-03-16 13:22:54 web           |   errno: -111,
2024-03-16 13:22:54 web           |   code: 'ECONNREFUSED',
2024-03-16 13:22:54 web           |   syscall: 'connect',
2024-03-16 13:22:54 web           |   address: '127.0.0.1',
2024-03-16 13:22:54 web           |   port: 54321

**Comment by colesnic** [comment]
I can take a look at this
