### ISSUE TITLE
[Bug]: Unable to create brain or add knowledge

### ISSUE THREAD

**Issue by llwp** [QuivrHQ/quivr#2389]
### What happened?

New local install, following documentation.  Everything comes up and login permitted.

However, when trying to "Add New Brain", upon clicking on button, a number of errors stream in the back-end and the dialogs do not appear fully loaded:
![Screenshot 2024-03-29 111826](https://github.com/QuivrHQ/quivr/assets/9566542/696873a0-1186-4fb8-b87b-0172928f81f9)

There is a backend error for `GET /prompts` as well, which looks largely similar to this one:
```
backend-core  | INFO:     172.30.0.1:36672 - "GET /brains/ HTTP/1.1" 500 Internal Server Error
backend-core  | ERROR:    Exception in ASGI application
backend-core  | Traceback (most recent call last):
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
backend-core  |     yield
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 228, in handle_request
backend-core  |     resp = self._pool.handle_request(req)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
backend-core  |     raise exc from None
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
backend-core  |     response = connection.handle_request(
backend-core  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
backend-core  |     stream = self._connect(request)
backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 122, in _connect
backend-core  |     stream = self._network_backend.connect_tcp(**kwargs)
backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
backend-core  |     with map_exceptions(exc_map):
backend-core  |   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
backend-core  |     self.gen.throw(typ, value, traceback)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
backend-core  |     raise to_exc(exc) from exc
backend-core  | httpcore.ConnectError: [Errno -2] Name or service not known
backend-core  |
backend-core  | The above exception was the direct cause of the following exception:
backend-core  |
backend-core  | Traceback (most recent call last):
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
backend-core  |     result = await app(  # type: ignore[func-returns-value]
backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
backend-core  |     return await self.app(scope, receive, send)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
backend-core  |     await super().__call__(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
backend-core  |     await self.middleware_stack(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
backend-core  |     await self.app(scope, receive, _send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
backend-core  |     await self.simple_response(scope, receive, send, request_headers=headers)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
backend-core  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-core  |     await app(scope, receive, sender)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
backend-core  |     await self.middleware_stack(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
backend-core  |     await route.handle(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
backend-core  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-core  |     await app(scope, receive, sender)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
backend-core  |     response = await func(request)
backend-core  |                ^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
backend-core  |     raw_response = await run_endpoint_function(
backend-core  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
backend-core  |     return await dependant.call(**values)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/modules/brain/controller/brain_routes.py", line 49, in retrieve_all_brains_for_user
backend-core  |     brains = brain_user_service.get_user_brains(current_user.id)
backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/modules/brain/service/brain_user_service.py", line 123, in get_user_brains
backend-core  |     results = self.brain_user_repository.get_user_brains(user_id)  # type: ignore
backend-core  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/modules/brain/repository/brains_users.py", line 42, in get_user_brains
backend-core  |     .execute()
backend-core  |      ^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/postgrest/_sync/request_builder.py", line 58, in execute
backend-core  |     r = self.session.request(
backend-core  |         ^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 814, in request
backend-core  |     return self.send(request, auth=auth, follow_redirects=follow_redirects)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 901, in send
backend-core  |     response = self._send_handling_auth(
backend-core  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 929, in _send_handling_auth
backend-core  |     response = self._send_handling_redirects(
backend-core  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
backend-core  |     response = self._send_single_request(request)
backend-core  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1002, in _send_single_request
backend-core  |     response = transport.handle_request(request)
backend-core  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 227, in handle_request
backend-core  |     with map_httpcore_exceptions():
backend-core  |   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
backend-core  |     self.gen.throw(typ, value, traceback)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
backend-core  |     raise mapped_exc(message) from exc
backend-core  | httpx.ConnectError: [Errno -2] Name or service not known
```

Obviously, "Name or service not known" is the most plain language part of this - as yet I am unclear what it is trying to reach.

**Comment by llwp** [comment]
Added the `extra_hosts` value and explicitly replaced localhost with my local ip address. (1 & 2 suggested)

Not sure if it was one or both of these, but the initial problem appears resolved.

New prompt to create an account once logged in, and "add brain" dialog is populated.  Backend logs are *flying* ... lots of traffic; but appears to have moved past the initial problem.

**Comment by llwp** [comment]
Wondering if there is something the startup docs would benefit on this .. great that the bot picked this up, but seems like there is something to improve.  Just not sure what.  I'll close this issue as the matter is resolved.
