### ISSUE TITLE
[Bug]: Setting up locally shows screen "Talk to Quivr  Unpaid users have access to a free and limited demo of Quivr"

### ISSUE THREAD

**Issue by opendeluxe** [QuivrHQ/quivr#2545]
### What happened?

I setup the full stack locally on my macbook as described in the README. All docker containers are running well without any issues. However, when opening `http://localhost:3000/login` in a webbrowser, it only shows the logo and the text 
"Talk to Quivr Unpaid users have access to a free and limited demo of Quivr"

<img width="749" alt="Screenshot 2024-05-05 at 23 03 12" src="https://github.com/QuivrHQ/quivr/assets/132100527/200602a0-d122-4d76-89dc-0d643e02225f">

According to the log, it seems to call some /user endpoints which respond with 403. I would expect that the login-form would be rendered instead first.

### Relevant log output

```bash
beat          | [2024-05-05 21:05:00,000: INFO/MainProcess] Scheduler: Sending due task process_integration_brain_sync (celery_worker.process_integration_brain_sync)
worker        | [2024-05-05 21:05:00,012: INFO/MainProcess] Task celery_worker.process_integration_brain_sync[7da1bf77-3ee6-49cd-9c7f-05f9f2fd72f0] received
worker        | [2024-05-05 21:05:00,045: INFO/ForkPoolWorker-2] HTTP Request: GET http://host.docker.internal:54321/rest/v1/integrations_user?select=%2A%2C%20integrations%20%28%29&integrations.integration_name=eq.notion "HTTP/1.1 200 OK"
worker        | [2024-05-05 21:05:00,057: INFO/ForkPoolWorker-2] Task celery_worker.process_integration_brain_sync[7da1bf77-3ee6-49cd-9c7f-05f9f2fd72f0] succeeded in 0.040312542000037865s: Noneer Desktop   w Enable Watch
backend-core  | INFO:     127.0.0.1:37474 - "GET /healthz HTTP/1.1" 200 OK
backend-core  | INFO:     127.0.0.1:60676 - "GET /healthz HTTP/1.1" 200 OK
backend-core  | INFO:     127.0.0.1:42342 - "GET /healthz HTTP/1.1" 200 OK
backend-core  | INFO:     127.0.0.1:45582 - "GET /healthz HTTP/1.1" 200 OK
backend-core  | INFO:     127.0.0.1:45830 - "GET /healthz HTTP/1.1" 200 OK
backend-core  | INFO:     127.0.0.1:41716 - "GET /healthz HTTP/1.1" 200 OK
backend-core  | INFO:     127.0.0.1:59444 - "GET /healthz HTTP/1.1" 200 OK
backend-core  | INFO:     127.0.0.1:54708 - "GET /healthz HTTP/1.1" 200 OK
backend-core  | INFO:     192.168.65.1:53110 - "OPTIONS /user/credits HTTP/1.1" 200 OK
backend-core  | INFO:     192.168.65.1:53108 - "OPTIONS /user HTTP/1.1" 200 OK
backend-core  | INFO:     192.168.65.1:53109 - "OPTIONS /user/identity HTTP/1.1" 200 OK
backend-core  | INFO:     192.168.65.1:53114 - "GET /user HTTP/1.1" 403 Forbidden
backend-core  | INFO:     192.168.65.1:53112 - "GET /user/identity HTTP/1.1" 403 Forbidden
backend-core  | INFO:     192.168.65.1:53113 - "GET /user/credits HTTP/1.1" 403 Forbidden
backend-core  | INFO:     192.168.65.1:53112 - "GET /user/identity HTTP/1.1" 403 Forbidden
backend-core  | INFO:     192.168.65.1:53113 - "GET /user HTTP/1.1" 403 Forbidden
backend-core  | INFO:     192.168.65.1:53112 - "GET /user HTTP/1.1" 403 Forbidden
backend-core  | INFO:     192.168.65.1:53113 - "GET /user/identity HTTP/1.1" 403 Forbidden
backend-core  | INFO:     192.168.65.1:53112 - "GET /user/identity HTTP/1.1" 403 Forbidden
backend-core  | INFO:     192.168.65.1:53113 - "GET /user HTTP/1.1" 403 Forbidden
backend-core  | INFO:     127.0.0.1:56056 - "GET /healthz HTTP/1.1" 200 OK
backend-core  | INFO:     127.0.0.1:57530 - "GET /healthz HTTP/1.1" 200 OK
beat          | [2024-05-05 21:10:00,037: INFO/MainProcess] Scheduler: Sending due task process_integration_brain_sync (celery_worker.process_integration_brain_sync)
worker        | [2024-05-05 21:10:00,048: INFO/MainProcess] Task celery_worker.process_integration_brain_sync[df4ede5e-3ab4-4149-8850-5ab979e52130] received
worker        | [2024-05-05 21:10:00,071: INFO/ForkPoolWorker-2] HTTP Request: GET http://host.docker.internal:54321/rest/v1/integrations_user?select=%2A%2C%20integrations%20%28%29&integrations.integration_name=eq.notion "HTTP/1.1 200 OK"
worker        | [2024-05-05 21:10:00,073: INFO/ForkPoolWorker-2] Task celery_worker.process_integration_brain_sync[df4ede5e-3ab4-4149-8850-5ab979e52130] succeeded in 0.02032537499985665s: Noneker Desktop   w Enable Watch
backend-core  | INFO:     127.0.0.1:38962 - "GET /healthz HTTP/1.1" 200 OK
backend-core  | INFO:     127.0.0.1:43536 - "GET /healthz HTTP/1.1" 200 OK
backend-core  | INFO:     127.0.0.1:51506 - "GET /healthz HTTP/1.1" 200 OK
```

**Comment by powderblock** [comment]
Having the same issue after updating my local codebase to match the code found in newest version of main branch. It was working previously with a version from ~2 weeks ago.

**Comment by sgwaterwoods** [comment]
I have exactly same issue

**Comment by dazeb** [comment]
Same issue here. Came back to test after it not working last time and now this 😂

**Comment by opendeluxe** [comment]
I think the README needs some further adjustments after recent changes

**Comment by 4ku** [comment]
What is the last workable version?

**Comment by BestLemoon** [comment]
> Having the same issue after pulling the newest version of main branch. It was working previously with a version from ~2 weeks ago.

Hi, what is the last workable version, thank you.

**Comment by sgwaterwoods** [comment]
I saw some update made a few hours ago and execute git pull and supabase migration up and get the following error. 

Connecting to local database...
runtime error: slice bounds out of range [1:0]
Try rerunning the command with --debug to troubleshoot the error. 

The issue is still there.

**Comment by 4ku** [comment]
@StanGirard any ideas?

**Comment by StanGirard** [comment]
Add `NEXT_PUBLIC_AUTH_MODES=password` to your env file :D

**Comment by 4ku** [comment]
@StanGirard It doesn't help, unfortunately (

**Comment by sweatybridge** [comment]
```
Connecting to local database...
runtime error: slice bounds out of range [1:0]
Try rerunning the command with --debug to troubleshoot the error.
```

This could be a supabase issue that we fixed recently. You can try `npx supabase@beta migration up` instead.

**Comment by StanGirard** [comment]
Sorry about that, forgot to add the variable to the docker compose too. 

Please git pull and docker compose up --build

**Comment by StanGirard** [comment]
@sweatybridge  you could try a `supabase db reset` too :)

**Comment by 4ku** [comment]
@StanGirard Now it works! But I have another error while creating first brain:

```
backend-core  | USER_IDENTITY {'user_id': '39418e3b-0258-4452-af60-7acfcc1263ff', 'openai_api_key': None, 'company': '', 'onboarded': True, 'username': 'www', 'company_size': None, 'usage_purpose': ''}
backend-core  | INFO:     172.21.0.1:33786 - "PUT /user/identity HTTP/1.1" 200 OK
backend-core  | INFO:     172.21.0.1:33786 - "OPTIONS /brains/ HTTP/1.1" 200 OK
backend-core  | INFO:     172.21.0.1:33786 - "POST /brains/ HTTP/1.1" 500 Internal Server Error
backend-core  | ERROR:    Exception in ASGI application
backend-core  | Traceback (most recent call last):
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
backend-core  |     result = await app(  # type: ignore[func-returns-value]
backend-core  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
backend-core  |     return await self.app(scope, receive, send)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
backend-core  |     await super().__call__(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
backend-core  |     await self.middleware_stack(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
backend-core  |     await self.app(scope, receive, _send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 93, in __call__
backend-core  |     await self.simple_response(scope, receive, send, request_headers=headers)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 148, in simple_response
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
backend-core  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-core  |     await app(scope, receive, sender)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
backend-core  |     await self.middleware_stack(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
backend-core  |     await route.handle(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
backend-core  |     await self.app(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
backend-core  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
backend-core  |     raise exc
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-core  |     await app(scope, receive, sender)
backend-core  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
backend-core  |     response = await func(request)
backend-core  |                ^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
backend-core  |     raw_response = await run_endpoint_function(
backend-core  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
backend-core  |     return await dependant.call(**values)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/modules/brain/controller/brain_routes.py", line 103, in create_new_brain
backend-core  |     new_brain = brain_service.create_brain(
backend-core  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/modules/brain/service/brain_service.py", line 142, in create_brain
backend-core  |     return self.create_brain_integration(user_id, brain)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/modules/brain/service/brain_service.py", line 192, in create_brain_integration
backend-core  |     created_brain = self.brain_repository.create_brain(brain)
backend-core  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/code/modules/brain/repository/brains.py", line 24, in create_brain
backend-core  |     brain_meaning = embeddings.embed_query(string_to_embed)
backend-core  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/langchain_openai/embeddings/base.py", line 530, in embed_query
backend-core  |     return self.embed_documents([text])[0]
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/langchain_openai/embeddings/base.py", line 489, in embed_documents
backend-core  |     return self._get_len_safe_embeddings(texts, engine=engine)
backend-core  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/langchain_openai/embeddings/base.py", line 347, in _get_len_safe_embeddings
backend-core  |     response = self.client.create(
backend-core  |                ^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/openai/resources/embeddings.py", line 114, in create
backend-core  |     return self._post(
backend-core  |            ^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1240, in post
backend-core  |     return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
backend-core  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 921, in request
backend-core  |     return self._request(
backend-core  |            ^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1020, in _request
backend-core  |     raise self._make_status_error_from_response(err.response) from None
backend-core  | openai.PermissionDeniedError: Error code: 403 - {'error': {'code': 'unsupported_country_region_territory', 'message': 'Country, region, or territory not supported', 'param': None, 'type': 'request_forbidden'}}
backend-core  | INFO:     127.0.0.1:53244 - "GET /healthz HTTP/1.1" 200 OK
```

**Comment by 4ku** [comment]
Fixed previous error wth VPN, thanks
