### ISSUE TITLE
[Bug]: UnpickleableExceptionWrapper('postgrest.exceptions', 'APIError', ('{\'code\': \'42P01\', \'details\': None, \'hint\': None, \'message\': \'relation "public.syncs_active" does not exist\'}',), 'Error 42P01:\nMessage: relation "public.syncs_active" does not exist')

### ISSUE THREAD

**Issue by littlezbq** [QuivrHQ/quivr#2617]
### What happened?

i follow exactly as the documentation to deploy quivr and it succeed. I can create brain and upload files to it, but when I try to talk to my brain, he returned nothing but a blank to me,  and the page didn't jump any error windows.
hope someone can help me figure out what happened

### Relevant log output

```bash
worker        | [2024-05-25 08:40:00,013: INFO/MainProcess] Task process_sync_active[09035e44-ef66-44a0-9038-c1498a54762e] received
worker        | [2024-05-25 08:40:00,015: INFO/MainProcess] Task celery_worker.process_integration_brain_sync[401a9420-33ba-4ffa-9d8a-fb32bd16a3d1] received
worker        | [2024-05-25 08:40:00,033: INFO/ForkPoolWorker-7] HTTP Request: GET http://host.docker.internal:54321/rest/v1/syncs_active?select=%2A&last_synced=lt.2024-05-25T02%3A40%3A00.016987 "HTTP/1.1 404 Not Found"
worker        | [2024-05-25 08:40:00,033: INFO/ForkPoolWorker-8] HTTP Request: GET http://host.docker.internal:54321/rest/v1/integrations_user?select=%2A%2C%20integrations%20%28%29&integrations.integration_name=eq.notion "HTTP/1.1 200 OK"
worker        | [2024-05-25 08:40:00,039: ERROR/ForkPoolWorker-7] Task process_sync_active[09035e44-ef66-44a0-9038-c1498a54762e] raised unexpected: UnpickleableExceptionWrapper('postgrest.exceptions', 'APIError', ('{\'code\': \'42P01\', \'details\': None, \'hint\': None, \'message\': \'relation "public.syncs_active" does not exist\'}',), 'Error 42P01:\nMessage: relation "public.syncs_active" does not exist')
worker        | Traceback (most recent call last):
worker        |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 453, in trace_task
worker        |     R = retval = fun(*args, **kwargs)
worker        |                  ^^^^^^^^^^^^^^^^^^^^
worker        |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 736, in __protected_call__
worker        |     return self.run(*args, **kwargs)
worker        |            ^^^^^^^^^^^^^^^^^^^^^^^^^
worker        |   File "/code/modules/sync/tasks.py", line 17, in process_sync_active
worker        |     loop.run_until_complete(_process_sync_active())
worker        |   File "/usr/local/lib/python3.11/site-packages/nest_asyncio.py", line 98, in run_until_complete
worker        |     return f.result()
worker        |            ^^^^^^^^^^
worker        |   File "/usr/local/lib/python3.11/asyncio/futures.py", line 203, in result
worker        |     raise self._exception.with_traceback(self._exception_tb)
worker        |   File "/usr/local/lib/python3.11/asyncio/tasks.py", line 277, in __step
worker        |     result = coro.send(None)
worker        |              ^^^^^^^^^^^^^^^
worker        |   File "/code/modules/sync/tasks.py", line 39, in _process_sync_active
worker        |     active = await sync_active_service.get_syncs_active_in_interval()
worker        |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker        |   File "/code/modules/sync/service/sync_service.py", line 79, in get_syncs_active_in_interval
worker        |     return await self.repository.get_syncs_active_in_interval()
worker        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker        |   File "/code/modules/sync/repository/sync.py", line 183, in get_syncs_active_in_interval
worker        |     .execute()
worker        |      ^^^^^^^^^
worker        |   File "/usr/local/lib/python3.11/site-packages/postgrest/_sync/request_builder.py", line 78, in execute
worker        |     raise APIError(r.json())
worker        | celery.utils.serialization.UnpickleableExceptionWrapper: Error 42P01:
worker        | Message: relation "public.syncs_active" does not exist
worker        | [2024-05-25 08:40:00,043: INFO/ForkPoolWorker-8] Task celery_worker.process_integration_brain_sync[401a9420-33ba-4ffa-9d8a-fb32bd16a3d1] succeeded in 0.02665457400144078s: None
```

**Comment by littlezbq** [comment]
it works, no error like this anymore, but the brain still return blank to me, no error in logs checked on docker.
