### ISSUE TITLE
[Bug]: 500 Internal server error

### ISSUE THREAD

**Issue by atulgrover** [QuivrHQ/quivr#2938]
### What happened?

1. The "localhost:3000" redirects to  "http://localhost:3000/v1" and throws a "500 Internal Server Error"....
2. The "//localhost:54323/project/default" redirects to "//localhost:54323/auth/v1" which returns a 404 'ERR_INVALID_URL'

### Relevant log output

```bash
024-08-02 23:30:45   digest: '2329514671'
2024-08-02 23:30:45 }
2024-08-02 23:30:45 TypeError [ERR_INVALID_URL]: Invalid URL
2024-08-02 23:30:45     at new NodeError (node:internal/errors:405:5)
2024-08-02 23:30:45     at new URL (node:internal/url:676:13)
2024-08-02 23:30:45     at new ty (/app/.next/server/chunks/491.js:105:28383)
2024-08-02 23:30:45     at tb (/app/.next/server/chunks/491.js:105:31441)
2024-08-02 23:30:45     at tW (/app/.next/server/chunks/491.js:105:37473)
2024-08-02 23:30:45     at u (/app/.next/server/chunks/491.js:14:441106)
2024-08-02 23:30:45     at C (/app/.next/server/chunks/809.js:26:22507)
2024-08-02 23:30:45     at em (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131226)
2024-08-02 23:30:45     at /app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142926
2024-08-02 23:30:45     at Array.toJSON (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146504) {
2024-08-02 23:30:45   input: '://localhost:54323/auth/v1',
2024-08-02 23:30:45   code: 'ERR_INVALID_URL'
2024-08-02 23:30:45 }
2024-08-02 23:30:45 [Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
2024-08-02 23:30:45   digest: '2329514671'
2024-08-02 23:30:45 }
```

**Comment by atulgrover** [comment]
1.The "http://localhost:54321/" throws up  {"message":"no Route matched with those values"}
2. I can access the "http://localhost:54323/project/default" supabase dashboard
